# Generated by Django 6.0.4 on 2026-05-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tawhidapp', '0002_addcashmodel_expendcashmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcashmodel',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='expendcashmodel',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
