# Generated by Django 6.0.4 on 2026-05-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tawhidapp', '0003_alter_addcashmodel_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcashmodel',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expendcashmodel',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
